### PR TITLE
fix(headless-ssr): fix `setAccessToken` for ssr commerce

### LINKED ISSUE #6292: [Headless SSR] - setAccessToken does not propagate unless building another engine
**Jira Issue:** [KIT-5113](https://coveord.atlassian.net/browse/KIT-5113)

**Type:** Bug
**Status:** Merged
**Priority:** Medium
**Components:** Headless

---

## Description

[https://discuss.coveo.com/t/headless-access-token-update-seems-to-require-full-page-reload-after-token-change/13774](https://discuss.coveo.com/t/headless-access-token-update-seems-to-require-full-page-reload-after-token-change/13774)

**Assignee:** Yassine Lakhdar

[KIT-5113]: https://coveord.atlassian.net/browse/KIT-5113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by y-lakhdar**
Enhanced access token management now supports dynamic token updates at any point in the SSR workflow, eliminating previous timing constraints.

- **Before**: `setAccessToken` had to be called before any engine was created (e.g., before fetching the static state). Calling it afterward (e.g. at post-hydration) would not propagate the change to already created controllers.
- **Now**: The access token update logic detects whether an engine has already been created and executes the appropriate update flow accordingly.

> I applied to fix to both `current` and `next` versions of headless ssr

https://coveord.atlassian.net/browse/KIT-5113

Fixes #6292

### CODE REVIEW

File: packages/headless/src/ssr/commerce/factories/build-factory.ts [hunk 1]
```diff
@@ -7,6 +7,7 @@ import {
 import {buildLogger} from '../../../app/logger.js';
 import {stateKey} from '../../../app/state-key.js';
 import type {Controller} from '../../../controllers/controller/headless-controller.js';
+import {loadConfigurationActions} from '../../../features/commerce/configuration/configuration-actions-loader.js';
```
Comment (vhilotii-coveo) [inline packages/headless/src/ssr/commerce/factories/build-factory.ts]: can we use alias ?

File: packages/headless/src/ssr-next/commerce/utils/access-token-manager.test.ts [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+
+    it('should handle multiple token updates before callback registration', () => {
+      tokenManager.setAccessToken('token-1');
+      tokenManager.setAccessToken('token-2');
+      tokenManager.setAccessToken('final-token');
+
+      const mockCallback = vi.fn();
+      tokenManager.registerCallback(mockCallback);
+
+      // Should only receive the latest token
```
Comment (vhilotii-coveo) [inline packages/headless/src/ssr-next/commerce/utils/access-token-manager.test.ts]: Is this comment needed?

**Review by vhilotii-coveo — APPROVED** [review]
LGTM after comments : )
